// +build !ignore_autogenerated

/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	timex "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultControllerConfiguration) DeepCopyInto(out *DefaultControllerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultControllerConfiguration.
func (in *DefaultControllerConfiguration) DeepCopy() *DefaultControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(DefaultControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DefaultControllerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultControllerConfigurationHealth) DeepCopyInto(out *DefaultControllerConfigurationHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultControllerConfigurationHealth.
func (in *DefaultControllerConfigurationHealth) DeepCopy() *DefaultControllerConfigurationHealth {
	if in == nil {
		return nil
	}
	out := new(DefaultControllerConfigurationHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultControllerConfigurationLeaderElection) DeepCopyInto(out *DefaultControllerConfigurationLeaderElection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultControllerConfigurationLeaderElection.
func (in *DefaultControllerConfigurationLeaderElection) DeepCopy() *DefaultControllerConfigurationLeaderElection {
	if in == nil {
		return nil
	}
	out := new(DefaultControllerConfigurationLeaderElection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultControllerConfigurationSpec) DeepCopyInto(out *DefaultControllerConfigurationSpec) {
	*out = *in
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(timex.Duration)
		**out = **in
	}
	out.LeaderElection = in.LeaderElection
	if in.LeaseDuration != nil {
		in, out := &in.LeaseDuration, &out.LeaseDuration
		*out = new(timex.Duration)
		**out = **in
	}
	if in.RenewDeadline != nil {
		in, out := &in.RenewDeadline, &out.RenewDeadline
		*out = new(timex.Duration)
		**out = **in
	}
	if in.RetryPeriod != nil {
		in, out := &in.RetryPeriod, &out.RetryPeriod
		*out = new(timex.Duration)
		**out = **in
	}
	out.Health = in.Health
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultControllerConfigurationSpec.
func (in *DefaultControllerConfigurationSpec) DeepCopy() *DefaultControllerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(DefaultControllerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultControllerConfigurationStatus) DeepCopyInto(out *DefaultControllerConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultControllerConfigurationStatus.
func (in *DefaultControllerConfigurationStatus) DeepCopy() *DefaultControllerConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultControllerConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
